@ECHO OFF
ECHO THIS BATCH IS FOR DEBUGGING THE EXECUTABLE JAR ONLY
ECHO DOUBLE-CLICK THE "arios-gamepack(signed).jar" TO RUN IT
ECHO -
ECHO Generated by: JAR Maker (http://www.goldenstudios.or.id/)
@ECHO ON
java -jar arios-gamepack(signed).jar
@ECHO OFF
pause
